#!/bin/bash

echo '=================> Ch0'
python3 transform_decfac.py 0
echo '=================> Ch1'
python3 transform_decfac.py 1
echo '=================> Ch2'
python3 transform_decfac.py 2
echo '=================> Ch3'
python3 transform_decfac.py 3
echo '=================> Ch4'
python3 transform_decfac.py 4
echo '=================> Ch5'
python3 transform_decfac.py 5
echo '=================> Ch6'
python3 transform_decfac.py 6
echo '=================> Ch7'
python3 transform_decfac.py 7
